name: wann-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.8.0
  - numpy=1.26.3
  - pandas=2.1.4
  - pillow=10.2.0
  - python=3.9.18
  - pytorch=2.2.0
  - pytorch-cuda=12.1
  - pytorch-lightning=2.1.3
  - pyyaml=6.0.1
  - scikit-learn=1.3.0
  - scipy=1.11.4
  - timm=0.9.16
  - torchvision=0.17.0
  - tqdm=4.65.0
  - pip:
      - imageio==2.34.0
      - medmnist==3.0.1
      - psutil==5.9.8
      - scikit-image==0.22.0
      - torchmetrics==1.3.1
      - wandb==0.16.3
